---
# tasks file for centos_default

- name: Get the current version of the kernel
  command: uname -r
  changed_when: false
  register: kernel_release

- name: Update the existing packages.
  yum:
    name: '*'
    state: latest

- name: Installing necessary packages
  yum:
    name: "{{ default_packages_for_centos }}"
    state: present

# Virtual box tool installation

- name: Check if Virtualbox is running on the guest VM.
  stat: path=/home/vagrant/.vbox_version
  register: virtualbox_check

- include_tasks: virtualbox.yml
  when: virtualbox_check.stat.exists

# Clean up tasks
# warn=false to prevent ansible warning using the command
- name: Remove unneeded packages
  yum:
    name:
      - cpp
      - kernel-devel
      - kernel-headers
    state: absent

- name: Clean yum
  command: >
    yum clean all
    warn=false 
  changed_when: true

- name: Remove any remnants of VirtualBox ISOs.
  shell: >
    rm -rf VBoxGuestAdditions_*.iso VBoxGuestAdditions_*.iso.?
    warn=false

