---
# Installs python3.8.5 package
  - name: Install some necessary yum packages.
    yum:
      name:
        - gcc
        - openssl-devel
        - bzip2-devel
        - libffi-devel
      state: present

  - name: Download the python 3.8.5 tar package.
    get_url:
      url: https://www.python.org/ftp/python/3.8.5/Python-3.8.5.tgz
      dest: /home/vagrant/Python-3.8.5.tgz
      mode: '0440'

  - name: Untar the archive
    unarchive:
      src: /home/vagrant/Python-3.8.5.tgz
      dest: /home/vagrant/
      remote_src: yes

  - name: configure --enable-optimizations
    command: /home/vagrant/Python-3.8.5/configure --enable-optimizations
    args:
      chdir: /home/vagrant/Python-3.8.5

  - name: Execute a shell script in /home/vagrant
    command:
      argv:
        - /usr/bin/make
        - altinstall
    args:
      chdir: /home/vagrant/Python-3.8.5